### ISSUE TITLE
Serialization format for data_tamer

### ISSUE THREAD

**Issue by Alex-Beh** [PickNikRobotics/data_tamer#12]
Hi, I would like to understand more about the serialization format of data_tamer. I saw the header file that you provided, however deserialize it in python because I need to use another module which is written in Python.

By going through the code, I understand the msg_buffer consist of 
```
<mask_size> <active_mask> <data_size> <serialized payload one after the other....>
```
Am I correct?

so with the following example,
```
  int32_t v3 = 129;
  uint16_t v4 = 129;
  
  Pose pose;
  pose.pos = {4, 4, 4};
  pose.rot = {4,4,4,4};

  channelA->registerValue("val_int32", &v3);
  channelA->registerValue("val_int16", &v4);
  channelA->registerValue("pose", &pose);
```

The message_buffer in bytestring is:
```
01 00 00 00 <--- mask_size
ff <--- active_mask
3e 00 00 00 <-- data_size
81 00 00 00 <-- v3
81 00 <-- v4
00 00 00 00 00 00 10 40 <-- should be pose.pose.x, but the encoding is weird.... am I wrong?
00 00 00 00 00 00 10 40 
00 00 00 00 00 00 10 40 
00 00 00 00 00 00 10 40 
00 00 00 00 00 00 10 40 
00 00 00 00 00 00 10 40 
00 00 00 00 00 00 10 40 
```

**Comment by facontidavide** [comment]
Hi Alex,

yes, I should write more about this topic, hopefully soon!

That is  a double, so it is perfectly normal. See here: https://www.binaryconvert.com/result_double.html?decimal=052

**Comment by facontidavide** [comment]
By the way, if you want to share your deserialization code in Python here, I will be happy to accept a PR!!!

**Comment by Alex-Beh** [comment]
Understood, the addressing is little-endian convention. Will try to open a PR once I finish ~
