### ISSUE TITLE
clang build error

### ISSUE THREAD

**Issue by adv4ncr** [PickNikRobotics/data_tamer#13]
Hi there,

I got the build error `data_tamer_cpp/include/data_tamer/channel.hpp:309:22: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]` followed by multiple successive errors in the same vain with using `clang17`. The self-reference could either be removed or the error suppressed.

Nice work by the way :grinning:

**Comment by facontidavide** [comment]
thanks, I will fix it
