### ISSUE TITLE
Log data not being written to disk

### ISSUE THREAD

**Issue by jlack1987** [PickNikRobotics/data_tamer#20]
I've been running into a case where I am logging to an mcap sink, but even after logging sometimes the mcap file is empty. I'm not sure if the issue has something to do with how the program exits or what. I'm sure there's some amount of buffered data that must accumulate before it writes to disk so perhaps that's in play as well :man_shrugging:. Below is a simple example that produces the behavior reliably for me. Basically I just run this and when I ctrl+c it the log file is still empty.

```c++
#include <iostream>
#include <unistd.h>
#include <data_tamer/data_tamer.hpp>
#include <data_tamer/sinks/mcap_sink.hpp>

int main(int /*argc*/, char** /*argv*/)
{
    std::shared_ptr<DataTamer::LogChannel> channel = DataTamer::LogChannel::create("test");
    channel->addDataSink(std::make_shared<DataTamer::MCAPSink>("/tmp/test.mcap"));

    double log_val = 0.;
    channel->registerValue("test_val", &log_val);
    while (true)
    {
        log_val++;
        channel->takeSnapshot();
        usleep(10000);
    }

    return 0;
}
```

**Comment by paLeziart** [comment]
@jlack1987 Data is only written to disk once the buffer is full. I think you are not waiting long enough in your case.

For instance if you modify the end of the `data_tamer_cpp/examples/T03_mcap_writer.cpp` example like that:
```
for(size_t i = 0; i < 10000; i++)
  {
    channelA->takeSnapshot();
    if(i % 2 == 0)
    {
      channelB->takeSnapshot();
    }
    std::this_thread::sleep_for(std::chrono::milliseconds(1));
  }
  std::cout << "WAIT" << std::endl;
  std::this_thread::sleep_for(std::chrono::milliseconds(10000));
  std::cout << "DONE" << std::endl;
```
If you press Ctrl+C once you see WAIT, the log file will contain some data because the buffer was filled at least once during the loop.

However, in any case, pressing Ctrl+C will "break" the mcap log file and you won't be able to read it with `data_tamer_cpp/examples/mcap_reader.cpp`. You have to close the sink properly by intercepting the Ctrl+C signal.

```
#include "data_tamer/data_tamer.hpp"
#include "data_tamer/sinks/mcap_sink.hpp"
#include "geometry_types.hpp"
#include <iostream>
#include <thread>
#include <signal.h>

using namespace DataTamer;

auto mcap_sink = std::make_shared<MCAPSink>("test_sample.mcap");

void signal_callback_handler(int signum) {
   std::cout << "Caught signal " << signum << std::endl;

   mcap_sink->~MCAPSink();

   // Terminate program
   std::exit(signum);
}

int main()
{
  signal(SIGINT, signal_callback_handler);

  ChannelsRegistry::Global().addDefaultSink(mcap_sink);

  // Create (or get) a channel using the global registry (singleton)
  auto channelA = ChannelsRegistry::Global().getChannel("channelA");
  auto channelB = ChannelsRegistry::Global().getChannel("channelB");

  // logs in channelA
  std::vector<double> v1(10, 0);
  std::array<float, 4> v2 = { 1, 2, 3, 4 };
  int32_t v3 = 5;
  uint16_t v4 = 6;
  TestTypes::Pose pose;
  pose.pos = { 1, 2, 3 };
  pose.rot = { 0.4, 0.5, 0.6, 0.7 };

  channelA->registerValue("vector_10", &v1);
  channelA->registerValue("array_4", &v2);
  channelA->registerValue("val_int32", &v3);
  channelA->registerValue("val_int16", &v4);
  channelA->registerValue("pose", &pose);

  // logs in channelB
  double v5 = 10;
  uint16_t v6 = 11;
  std::vector<uint8_t> v7(4, 12);
  std::array<uint32_t, 3> v8 = { 13, 14, 15 };
  std::vector<TestTypes::Point3D> points(2);
  points[0] = { 1, 2, 3 };
  points[1] = { 4, 5, 6 };

  channelB->registerValue("real_value", &v5);
  channelB->registerValue("short_int", &v6);
  channelB->registerValue("vector_4", &v7);
  channelB->registerValue("array_3", &v8);
  channelB->registerValue("points", &points);

  for(size_t i = 0; i < 10000; i++)
  {
    channelA->takeSnapshot();
    if(i % 2 == 0)
    {
      channelB->takeSnapshot();
    }
    std::this_thread::sleep_for(std::chrono::milliseconds(1));
  }
  std::cout << "WAIT" << std::endl;
  std::this_thread::sleep_for(std::chrono::milliseconds(10000));
  std::cout << "DONE" << std::endl;
}
```
I don't know if there is a better way to do it... 

If you don't do that, according to [https://github.com/foxglove/mcap/discussions/1093](https://github.com/foxglove/mcap/discussions/1093), it seems possible to fix the mcap file but I have not tried it.

**Comment by jlack1987** [comment]
ah ok thanks I appreciate it @paLeziart! Do you know if it's possible to modify the buffer size or at least where I can find what the buffer size is so I know how much I need to fill before it writes?

**Comment by paLeziart** [comment]
@jlack1987 The buffer size seems to be defined in `data_tamer_cpp/3rdparty/mcap/include/mcap/types.hpp` with `constexpr uint64_t DefaultChunkSize = 1024 * 768;` (so a size of 768 KB)

In `data_tamer_cpp/3rdparty/mcap/include/mcap/mcap.hpp` there is a `noChunking` option which might remove this buffer behaviour if set to true. I have not tried.
