### ISSUE TITLE
Automatically `RestartRecording` - Questionable default behavior

### ISSUE THREAD

**Issue by adv4ncr** [PickNikRobotics/data_tamer#31]
Hi Davide,
Thank you for creating such a great capture tool. We use it extensively in our research.
While recording a long dataset, I noticed the somewhat questionable default behavior of data_tamer to clear and restart the current measurement after 10 minutes:
https://github.com/PickNikRobotics/data_tamer/blob/5750ccf78208fa088d892e5bd67678ca4a45248a/data_tamer_cpp/src/sinks/mcap_sink.cpp#L121-L124
I have increased the reset time with `setMaxTimeBeforeReset()`, but the default behavior may not be obvious to many people, especially since the existing measurement file is overwritten without notice.
In my opinion it would be better not to automatically restart the measurement or to automatically create a new file with a counter appended to the filename.

What do you think?

Yours
Vinc

**Comment by henrygerardmoore** [comment]
I made #32 to allow for unlimited recording, please feel welcome to add a comment there on your preferred usage! There are a couple different options, and I'd be happy to implement any of them depending on your and @facontidavide's preferences.

**Comment by facontidavide** [comment]
I agree that default should change.
Creating a new file should also be an option
