### ISSUE TITLE
use protobuf for data encoding

### ISSUE THREAD

**Issue by asherikov** [PickNikRobotics/data_tamer#34]
Hello,

I suggest to switch to protobuf encoding instead of a custom protocol:
- this would make adaptation much easier, e.g., https://github.com/PickNikRobotics/data_tamer/issues/15;
- the protobuf schemas would provide clear documentation;
- protocol can be evolved much easier;
- protobuf is already supported in PlotJuggler, so most likely it would only be necessary to add custom handlers similar to pal_statisitcs.

How:
1. define protobuf schemas;
2. generate code using https://github.com/nanopb/nanopb, in order to avoid heavy dependencies on protobuf libraries and potential issues with library/generator compatibility;
3. generate protobuf binary descriptors with `protoc`;
4. embed descriptors in the source code;
5. at runtime write protobuf descriptors and messages to mcap as documented https://mcap.dev/guides/cpp/protobuf

I did a similar thing for a toy project -- it works.

**Comment by facontidavide** [comment]
I would arther have different encoding / plugins

**Comment by asherikov** [comment]
Hi,

1. ROS messages are also a schema, but it did not prevent pal_statistics_msgs from being implemented. My suggestion is to folow the same approach, i.e., define arrays of values.

2. Anyway, it would be nice to have a reusable standalone serialization library, that would be independent from ROS and could be used in alternative implementations that need to output data in PlotJuggler compatible format. Meanwhile I am building my own lunapark with plotjuggler_msgs and fastcdr -> https://github.com/asherikov/intrometry.
