### ISSUE TITLE
ROS dependency

### ISSUE THREAD

**Issue by asherikov** [PickNikRobotics/data_tamer#35]
The project should not assume that ROS2 support should be enabled based on availability of ament. It should be a an option that can be specififed by the user, or, even better, ROS and non-ROS parts should be separate packages.

**Comment by henrygerardmoore** [comment]
I created #36, take a look and let me know what you think. It may indeed be nicest in some regards to have separate packages, but as this project is relatively small with and without the ROS components, I think it might introduce more annoyance (when depending on data_tamer) than it provides in benefits.

**Comment by asherikov** [comment]
Thank you, overall ok, I left a couple of comments in the MR.

**Comment by asherikov** [comment]
Actually, there is a strong argument for splitting the package: package manifest still depends on rclcpp
